// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. yet',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeduU4K66wmICRshr1T7pbNV-wchLTjPo',
    appId: '1:447603365081:web:7ef4650d4bdfc43a70dac8',
    messagingSenderId: '447603365081',
    projectId: 'datasaver-b84f5',
    authDomain: 'datasaver-b84f5.firebaseapp.com',
    storageBucket: 'datasaver-b84f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0yPELrgQaa1BlvZvKqlsVVpsOELX-cs',
    appId: '1:447603365081:android:8d1a1b99c93a05b170dac8',
    messagingSenderId: '447603365081',
    projectId: 'datasaver-b84f5',
    storageBucket: 'datasaver-b84f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDUrNJQ1ZHIwtcaq73R_370OKgRGJXXo',
    appId: '1:447603365081:ios:8fb7facb51efdafe70dac8',
    messagingSenderId: '447603365081',
    projectId: 'datasaver-b84f5',
    storageBucket: 'datasaver-b84f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDUrNJQ1ZHIwtcaq73R_370OKgRGJXXo',
    appId: '1:447603365081:ios:8fb7facb51efdafe70dac8',
    messagingSenderId: '447603365081',
    projectId: 'datasaver-b84f5',
    storageBucket: 'datasaver-b84f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeduU4K66wmICRshr1T7pbNV-wchLTjPo',
    appId: '1:447603365081:web:e4da6c56589c41ec70dac8',
    messagingSenderId: '447603365081',
    projectId: 'datasaver-b84f5',
    authDomain: 'datasaver-b84f5.firebaseapp.com',
    storageBucket: 'datasaver-b84f5.firebasestorage.app',
  );
}
